project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!exercises/exercises.Rmd"
    - "!slides/[0-9]*.qmd"

website:
  page-navigation: true
  title: "R for Bioinformatics"
  description: "Learn to Analyze Genomics, Metagenomics, and Transcriptomics Data with R"
  site-url: "https://chiraltraining.github.io/R-Bioconductor/"
  favicon: "images/baseplot.png"
  
  repo-url: https://github.com/hossainlab/clinical-reporting-gtsummary-rmed
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@hossainlab"
    image: "/images/bioconductor.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Md. Jubayer Hossain"
    background: "#708090"

  sidebar:
    background: "#708090"
    logo: "images/baseplot.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/chiraltraining/
        text: GitHub
      - icon: facebook
        href: https://www.facebook.com/chiralbd.org
        text: Facebook
      - icon: twitter
        href: https://twitter.com/chiralbd
        text: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/company/chiral-bangladesh/mycompany/?viewAsMember=true
        text: LinkedIn
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: sessions.qmd
       text: Schedule
     - href: q-and-a.qmd
       text: FAQs
     - href: packages.qmd
     - href: resources.qmd
     - href: license.qmd
       text: License

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source

